### ISSUE TITLE
Longpolling error "400 Bad Request"

### ISSUE THREAD

**Issue by ska-ibees** [GlodoUK/helm-charts#5]
Hi,
Have you experienced any issues with longpolling with workers >0 ?
For all longpolling/* request I am having this error in console. 

"message": "400 Bad Request: <function Website.index at 0x7f49b470f700>, /: Function declared as capable of handling request of type 'http' but called with a request of type 'json'", "arguments": [], "context": {}}}}

It happens only for the backend (/web).

**Comment by theangryangel** [comment]
No issues that I can see in any of our live installations at the moment

with workers > 0 you should be pointing at the long polling port (we do that via https://github.com/GlodoUK/helm-charts/blob/0d9c788036a7d29f5198311a4539ee3ddcd445cb/odoo/templates/web/ingressroute.yaml#L24). That would be my first guess?

**Comment by ska-ibees** [comment]
@theangryangel Hey Man can't thanks enough to put me in the right direction. Its been three days in a row that I was scratching my head.
Infact, i already double checked all configs at all levels. However, Nginx ingress is not respecting it's rule for /longpolling rule. This is something unexpected that put me in a black hole. 
What is happening is that all traffic is forwarded to port 8069 thus causing that error. 
I think it's time to try traefik. The only thing in my use case is to have ability to add custom headers in the request.
Do you see any additional benefits of traefik over nginx?

**Comment by theangryangel** [comment]
We did test out nginx, and it worked fine for us (we needed to tweak a few things like the proxy timeouts, but it generally worked). I might be able to help out if you can drop in some sample configs?

Honestly we're only using Traefik still because we were using it when we were running Docker Swarm. The team have experience with how it worked, so we just kept it.

The main problem we've had that's still relevant for v2 is https://github.com/traefik/traefik/issues/3376. The short version of that issue is that the built-in lets encrypt support works great, until you remove an ingress/ingressroute. It will keep trying to renew that certificate until you manually remove it from it's json store.

To solve that we had to switch to cert-manager (I only added cert-manager support to the helm chart a few days ago, because we were rolling out slowly) because our IP range was repeatedly getting banned as we started up new demo/test instances and then deleted them.

We've had other issues with Traefik around early 2.0, but I can't think of any major issues we've had for quite some time.

Periodically I look at alternatives to Traefik, like Ambassador, HAProxy, etc. and either they dont have the features we need, or they don't bring any benefit.

**Comment by ska-ibees** [comment]
Today, I replaced nginx with traefik and was able to implement custom request header(one of the main custom requirement to host multiple domains with seperate DBs). 

Below is middleware config: 
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: domain3
  namespace: production
spec:
  headers:
  - customRequestHeaders:
      X-Odoo-dbfilter: ^proddb\Z
      X-Forwarded-Host: $host
      X-Forwarded-For: $proxy_add_x_forwarded_for
      X-Real-IP: $remote_addr
```
As of now getting error for:
      ```
X-Forwarded-Host: $host
      X-Forwarded-For: $proxy_add_x_forwarded_for
      X-Real-IP: $remote_addr

```
Would love to know how you are dealing with it?
Also, what about the caching in traefik? 


Well, i think Traefik is the way to go as I am not concerned about SSL termination/certifcates etc. I am using AWS Application load balancer to handle that stuff and just forwarding to Traefik over HTTP.

Thanks again!

**Comment by ska-ibees** [comment]
@theangryangel Sorry for the direct ping. May I know how you are dealing with X-Forwarded * headers with Traefik? Especially, how to get real client IP.

X-Forwarded-Host: $host
X-Forwarded-For: $proxy_add_x_forwarded_for
X-Real-IP: $remote_addr

Thanks!

**Comment by theangryangel** [comment]
Sorry I saw your message a few weeks ago and then completely forgot about it :( Super busy here at the moment!

The only special thing we do is add `externalTrafficPolicy: Local` to our Traefik service definition. After that Traefik does all the correct things for us out of the box - if you head to https://whoami.glodo.uk/ you should see the headers being added with the correct values our one of our live clusters.

Hope that helps :)

**Comment by theangryangel** [comment]
> My traefik instance is behind AWS's Application load balancer. Anyways, I think i need to dig into deeper with whoami and tracing.

Assuming the AWS loadbalancer sets the X-Forward-*, etc. headers you'll need to tell Traefik to trust them. There's this configuration here - https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-header that's probably the thing you're missing, I'd guess?

**Comment by ska-ibees** [comment]
After digging it more. It turned out that each proxy adds it's information so having multiple IPs in X-Forwarded-For (Left most) is a standard implementation. 
Being a standard implementation it is not something easily doable within Traefik unless using a custom plugin/middleware. However, luckily there is an option within Werkzueg ([Explained Here](https://werkzeug.palletsprojects.com/en/2.0.x/middleware/proxy_fix/))

So, had to monkeypatch Odoo... 

Value of x_for=2 solved this problem. 

[Odoo code](https://github.com/odoo/odoo/blob/9cdde27e25b13714e24082a50673454693c954ef/odoo/service/wsgi_server.py#L111)

**Comment by theangryangel** [comment]
I think we're done on this one Syed? Let me know if not :) I'm glad you got it working? :)

**Comment by ska-ibees** [comment]
Yes it is done. Thank you!
